# Generated by Django 6.0.8 on 2026-08-05 04:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('health_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('full_name', models.CharField(max_length=150)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='patient_photos/')),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('home_state', models.CharField(help_text="Worker's native state, e.g. West Bengal", max_length=100)),
                ('current_worksite', models.CharField(help_text='Current work location in Kerala', max_length=200)),
                ('preferred_language', models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('ml', 'Malayalam'), ('bn', 'Bengali'), ('or', 'Odia'), ('as', 'Assamese')], default='hi', max_length=5)),
                ('income_bracket', models.CharField(choices=[('below_2.5l', 'Below ₹2.5 Lakh / year'), ('2.5l_to_5l', '₹2.5 Lakh - ₹5 Lakh / year'), ('above_5l', 'Above ₹5 Lakh / year')], default='below_2.5l', max_length=20)),
                ('known_conditions', models.TextField(blank=True, help_text='Comma-separated, e.g. Hypertension, Type 2 Diabetes')),
                ('known_allergies', models.TextField(blank=True, help_text='Comma-separated allergies')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VisitRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinic_name', models.CharField(max_length=200)),
                ('visit_date', models.DateField(auto_now_add=True)),
                ('diagnosis', models.CharField(max_length=300)),
                ('medications_prescribed', models.TextField(help_text='e.g. Amlodipine 5mg - once daily')),
                ('doctor_notes', models.TextField(blank=True)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('uploaded_document', models.ImageField(blank=True, help_text='Photo of prescription or lab report', null=True, upload_to='visit_documents/')),
                ('ocr_extracted_text', models.TextField(blank=True, editable=False, help_text='Auto-filled by OCR when a document is uploaded')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits_logged', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='records.patient')),
            ],
            options={
                'ordering': ['-visit_date'],
            },
        ),
    ]
