# Generated by Django 5.2.17 on 2026-08-07 00:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_alter_clinicstaffprofile_id_alter_patient_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='visit_documents/')),
                ('ocr_extracted_text', models.TextField(blank=True, editable=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='records.visitrecord')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
    ]
