# Generated by Django 5.2.17 on 2026-08-07 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0006_health_features'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='healthmetric',
            options={},
        ),
        migrations.AlterModelOptions(
            name='medicinereminder',
            options={},
        ),
        migrations.RemoveField(
            model_name='healthmetric',
            name='diastolic_bp',
        ),
        migrations.RemoveField(
            model_name='healthmetric',
            name='systolic_bp',
        ),
        migrations.RemoveField(
            model_name='medicinereminder',
            name='active',
        ),
        migrations.RemoveField(
            model_name='medicinereminder',
            name='last_taken_at',
        ),
        migrations.RemoveField(
            model_name='medicinereminder',
            name='notes',
        ),
        migrations.AddField(
            model_name='healthmetric',
            name='blood_pressure',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='medicinereminder',
            name='taken',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='current_medicines',
            field=models.TextField(blank=True, help_text='Current medicines, comma-separated'),
        ),
        migrations.AddField(
            model_name='patient',
            name='last_follow_up',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='healthmetric',
            name='blood_sugar',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='healthmetric',
            name='recorded_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='healthmetric',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicinereminder',
            name='medicine_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='patient',
            name='blood_group',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='patient',
            name='bmi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='insurance_status',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='vaccination_status',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='worksite_history',
            field=models.TextField(blank=True, help_text='Previous worksites, comma-separated'),
        ),
    ]
