# Generated by Django 5.2.17 on 2026-08-07 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0007_alter_healthmetric_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='healthmetric',
            options={'ordering': ['recorded_at']},
        ),
        migrations.AlterModelOptions(
            name='medicinereminder',
            options={'ordering': ['time']},
        ),
        migrations.AlterField(
            model_name='patient',
            name='occupation',
            field=models.CharField(blank=True, help_text="Worker's occupation, e.g. Construction, Factory, Fishing", max_length=100),
        ),
    ]
