# Generated by Django 5.2.17 on 2026-08-07 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0008_alter_healthmetric_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicinereminder',
            options={},
        ),
        migrations.AddField(
            model_name='medicinereminder',
            name='taken_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
