# Generated by Django 5.2.17 on 2026-08-07 06:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0009_alter_medicinereminder_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicinereminder',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicinereminder',
            name='frequency',
            field=models.CharField(choices=[('daily', 'Every Day'), ('weekly', 'Every Week')], default='daily', max_length=10),
        ),
        migrations.AddField(
            model_name='medicinereminder',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddField(
            model_name='medicinereminder',
            name='weekly_day',
            field=models.IntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], null=True),
        ),
        migrations.CreateModel(
            name='MedicineDose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField()),
                ('scheduled_time', models.TimeField()),
                ('taken', models.BooleanField(default=False)),
                ('taken_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reminder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doses', to='records.medicinereminder')),
            ],
            options={
                'ordering': ['-scheduled_date', 'scheduled_time'],
                'constraints': [models.UniqueConstraint(fields=('reminder', 'scheduled_date'), name='unique_medicine_dose_per_day')],
            },
        ),
    ]
